version: '3.8'

services:
  postgres:
    image: registry.redhat.io/rhel9/postgresql-16
    container_name: collector-db
    environment:
      - POSTGRESQL_USER=${POSTGRES_USER:-metering}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-metering}
      - POSTGRESQL_DATABASE=${POSTGRES_DB:-metering}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-metering} -d ${POSTGRES_DB:-metering}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metering-network
    restart: always

  metering-collector:
    image: quay.io/chambrid/metering-collector:latest
    container_name: collector
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-metering}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-metering}
      - POSTGRES_DB=${POSTGRES_DB:-metering}
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - metering-network
    restart: on-failure

  partition-scripts:
    image: quay.io/chambrid/metering-collector:latest
    container_name: collector-init
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-metering}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-metering}
      - POSTGRES_DB=${POSTGRES_DB:-metering}
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "sleep 10 && /app/bin/migrate -database \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable\" -path /app/migrations up && /app/bin/create_daily_partitions && /app/bin/delete_old_partitions"
    networks:
      - metering-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  metering-network:
    driver: bridge
